# Generated by Django 4.1.2 on 2022-10-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(default='desc', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='venue',
            field=models.CharField(default='venue', max_length=50),
        ),
    ]
