# Generated by Django 4.1.2 on 2022-10-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_post_title_alter_post_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=models.FileField(default='', upload_to='videos/posts'),
        ),
    ]
