# Generated by Django 4.1.2 on 2022-10-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='match_id',
            field=models.CharField(default='match_id', max_length=30, unique=True),
        ),
    ]
