# Generated by Django 4.0.5 on 2022-10-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_post_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='match_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=models.FileField(max_length=200, upload_to='videos/posts'),
        ),
    ]
